[package]
name = "enseeiht-internship-report"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Victor Marti"]
license = "MIT"
description = "Template de rapport de stage pour l'ENSEEIHT."
keywords = ["template", "report", "internship", "enseeiht"]
categories = ["report"]

[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"